<?php
	class Constantes{
		const EXITO = true;
		const ERROR = false;
		const ERROR_USUARIO_Y_O_PASSWORD_INCORRECTOS = -100;
		const ERROR_USUARIO_REGISTRADO = -101;
		const ERROR_SIN_RESULTADOS = -200;
		const ERROR_SELECCION_NO_VALIDA = -201;
		const ERROR_SIN_RESULTADOS_DETALLE_OFERTA = -202;
		const ERROR_SIN_RESULTADOS_OFERTA_AREA = -203;
		const ERROR_SIN_RESULTADOS_OFERTA_SELECCIONADA = -204;
		const ERROR_INSERCION_CANDIDATO_NO_VALIDA = -300;
		const ERROR_INSERCION_EMPRESA_NO_VALIDA = -301;
		const ERROR_INSERCION_OFERTA_NO_VALIDA = -302;
		const ERROR_INSERCION_SELECCION_NO_VALIDA = -303;
		const ERROR_INSERCION_AREA_NO_VALIDA = -300;
	}
?>